### PR TITLE
fix: no module named 'psycopg2'

### LINKED ISSUE #3417: Issue: Pydantic - Portainer - Docker Swarm (PydanticDeprecatedSince20)
### Bug Description

Obs: I'm using Python 3.10.0

I'm trying to install Langflow on a portainer with docker swarm, however an error is appearing in the log that doesn't allow me to open the system.

### Reproduction

1. My Stack
```
version: "3.8"

services:
  langflow:
    image: langflowai/langflow:latest
    user: root
    depends_on:
      - postgres # Dependência no seu banco de dados existente
    volumes:
      - langflow_data:/var/lib/langflow
    networks:
      -  minha_rede
    environment:
      # Altere os dados do Banco de dados
      - LANGFLOW_DATABASE_URL=postgresql://postgres:xxxxxxxxxxx@postgres:5432/langflow
      # Segurança
      - LANGFLOW_SUPERUSER=xxxxxxxxx #crie o usuário de acesso
      - LANGFLOW_SUPERUSER_PASSWORD=xxxxxxxx #crie a senha de acesso
      - LANGFLOW_NEW_USER_IS_ACTIVE=true # Mude para false após o primeiro login
      - LANGFLOW_AUTO_LOGIN=false
      # Outros
      - LANGFLOW_CONFIG_DIR=/var/lib/langflow
      - BACKEND_URL=langflow.domain.com.br 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
        #analise os limites porque o Langflow consome bastante
          cpus: "1" 
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.langflow.rule=Host(langflow.domain.com.br)
        - traefik.http.routers.langflow.entrypoints=websecure
        - traefik.http.routers.langflow.tls.certresolver=letsencryptresolver
        - traefik.http.routers.langflow.service=langflow
        - traefik.http.services.langflow.loadbalancer.server.port=7860

volumes:
  langflow_data:
    external: true

networks:
  minha_rede:
    external: true
```

2. Log
```
Starting Langflow v1.0.15...
/app/.venv/lib/python3.12/site-packages/pysbd/segmenter.py:66: SyntaxWarning: invalid escape sequence '\s'
  for match in re.finditer('{0}\s*'.format(re.escape(sent)), self.original_text):
/app/.venv/lib/python3.12/site-packages/pysbd/lang/arabic.py:29: SyntaxWarning: invalid escape sequence '\.'
  txt = re.sub('(?<={0})\.'.format(am), '∯', txt)
/app/.venv/lib/python3.12/site-packages/pysbd/lang/persian.py:29: SyntaxWarning: invalid escape sequence '\.'
  txt = re.sub('(?<={0})\.'.format(am), '∯', txt)
/app/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
/app/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
  warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
/app/.venv/lib/python3.12/site-packages/litellm/utils.py:107: DeprecationWarning: open_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
  with resources.open_text("litellm.llms.tokenizers", "anthropic_tokenizer.json") as f:
[08/19/24 00:09:28] ERROR    2024-08-19 00:09:28 - ERROR    - setup setup.py:580
                             - Edge between Component and                       
                             CrewAIAgentComponent has invalid                   
                             handles                                            
[08/19/24 00:09:28] ERROR    2024-08-19 00:09:28 - ERROR    - setup setup.py:580
                             - Edge between Component and                       
                             CrewAIAgentComponent has invalid                   
                             handles                                            
[08/19/24 00:09:28] ERROR    2024-08-19 00:09:28 - ERROR    - setup setup.py:580
                             - Edge between Component and                       
                             CrewAIAgentComponent has invalid                   
                             handles                                            
╭───────────────────────────────────────────────────────────────────╮
│ Welcome to ⛓ Langflow                                             │
│                                                                   │
│                                                                   │
│ Collaborate, and contribute at our GitHub Repo 🌟                 │
│                                                                   │
│ We collect anonymous usage data to improve Langflow.              │
│ You can opt-out by setting DO_NOT_TRACK=true in your environment. │
│                                                                   │
│ Access http://0.0.0.0:7860                                        │
╰───────────────────────────────────────────────────────────────────╯
```
### Expected behavior

Access granted to the service

### Who can help?

@italojohnny

### Operating System

Ubuntu Linux 20.04.06

### Langflow Version

v1.0.15

### Python Version

3.10

### Screenshot

image

### Flow File

_No response_

### LINKED ISSUE #3517: No PostgreSQL driver in docker image for 1.0.16
### Bug Description

No PostgreSQL driver in docker image for 1.0.16 (No module named 'psycopg2')

### Reproduction

Install using docker image, connect to postgresql

### Expected behavior

psycopg2 is installed 

### Who can help?

_No response_

### Operating System

Ubuntu 22.04

### Langflow Version

1.0.16

### Python Version

None

### Screenshot

_No response_

### Flow File

_No response_

### LINKED ISSUE #3524: Docker 1.0.16 image does not work with Postgres
### Bug Description

Running `docker run -d langflowai/langflow:1.0.16` works just fine, but if you specify `-e LANGFLOW_DATABASE_URL=postgres://...` 

you get errors:
```sqlalchemy.exc.NoSuchModuleError: 
Can't load plugin:                
sqlalchemy.dialects:postgres      

import_dbapi                      
    import psycopg2               
ModuleNotFoundError: No module    
named 'psycopg2'                  
```

### Reproduction

Start a Docker instance for v1.0.16 that connects to a Postgres database using the `LANGFLOW_DATABASE_URL` environment vairable.

### Expected behavior

Container starts and Langflow service runs as normal :)

### Who can help?

_No response_

### Operating System

Langflow Docker image

### Langflow Version

1.0.16

### Python Version

3.12

### Screenshot

_No response_

### Flow File

_No response_

### PR DESCRIPTION
**Pull request by italojohnny**
Re-added psycopg2 dependency.

This PR fixes the following issues:
- Fixes #3517
- Fixes #3524
- Fixes #3417

### CODE REVIEW

**Comment by ogabrielluiz** [comment]
Actually, we need to add it back to the pyproject.toml.

**Review by jordanrfrazier — APPROVED** [review]

**Comment by hakan-77** [comment]
Hi @italojohnny, @ogabrielluiz 

pycopg is actually pycopg3 (https://pypi.org/project/psycopg/) so the move from pycopg2 to psycopg is a welcomed one, however, the reference was wrong in pyproject.toml (and docker)

Instead of pycopg we need to use pycopg[binary] or pycopg[binary, pool] (https://pypi.org/project/psycopg/)

After this, sqlalchemy will work with "postgresql+psycopg://.." instead of "postgresql+psycopg2://.." or just "postgresql://.." which defaults to psycopg2.

**Comment by italojohnny** [comment]
hi, @hakan-77 
Thank you very much for the tip. However, we think it's better to fix the problem as quickly as possible for now. But I will definitely consider this for future improvements

**Comment by mwebb33** [comment]
Thanks for being so quick on this. Gives me a lot of confidence in the project, recently picked it up and been quite impressed so far.

**Comment by hakan-77** [comment]
@italojohnny makes sense to migrate to pycopg3 after it becomes more mainstream, and the default PG dialect for sqlalchemy.

**Pull request merged**
