### PR TITLE
Fix: Fixes part of text input output component test where component popover elements are block others

### PR DESCRIPTION
**Pull request by 596050**
Description:
This pull request refactors the selection and interaction of elements in the textInputOutput.spec.ts test file to improve code readability and ensure proper functionality.

Changes:

- Consolidated the selection of elements using page.locator for better readability and maintainability.
- Elements are now stored in variables (component1, element1, component2, element2) for easier reference.
- Ensured that component popups are not blocking the elements by adding component1.blur() and component2.blur() before interactions.
- Refactored the drag-and-drop action for better clarity. Used element1.dragTo(element2) to move the first element to the second element's location dynamically.
- Left page.mouse.up() to ensure the mouse button is released after the drag-and-drop action.
- Removed redundant hover actions and streamlined the interaction process.

### CODE REVIEW

**Comment by Cristhianzl** [comment]
hi @596050,
thank you for your cooperation.

LGTM.

**Review by Cristhianzl — APPROVED** [review]

**Comment by 596050** [comment]
> hi @596050, thank you for your cooperation.
> 
> LGTM.

Hi, sure, we could offset the elements too? Should I create another PR to suggest that or add to this? I'm thinking:
```js
export const offsetElements = async ({
    sourceElement,
    targetElement,
    page,
}) => {

  // Get bounding boxes of the components
  const box1 = await sourceElement.boundingBox();
  const box2 = await targetElement.boundingBox();

  await page.mouse.move((box2?.x  || 0) + 10, (box2?.y || 0))
  await page.mouse.down();

  // Move to the right of the second component
  await page.mouse.move((box2?.x  || 0) + (box2?.width || 0)/2 + (box1?.width || 0), (box2?.y || 0));
  await page.mouse.up();
}
```

which becomes:
```js
  const component1 = await page.locator(
    '//*[@id="react-flow-id"]/div/div[1]/div/div/div[2]/div[1]',
  );

  const element1 = await page.locator(
    '//*[@id="react-flow-id"]/div/div[1]/div/div/div[2]/div[1]/div/div[2]/div[5]/button/div[1]',
  );

  const component2 = await page.locator(
    '//*[@id="react-flow-id"]/div/div[1]/div/div/div[2]/div[2]',
  );

  const element2 = await page.locator(
    '//*[@id="react-flow-id"]/div/div[1]/div/div/div[2]/div[2]/div/div[2]/div[3]/div/button/div[1]',
  );

  await offsetElements({
    sourceElement: component1,
    targetElement: component2,
    page,
  });

  // ensure elements popups are not blocking
  component1.blur();
  component2.blur();

  // Click and hold on the first element and move to the second element
  await element1?.dragTo(element2);

  // ensure the mouse button is up
  await page.mouse.up();
```
Which should do something like this:

textInputOutput

**Comment by Cristhianzl** [comment]
@596050 
this seems an error of replacing .env file on Github.
I'll check and let you

**Comment by Cristhianzl** [comment]
@596050 
It seems like the error is due to the OPENAI_API_KEY value not being found in the .env file in the GitHub environment. 
I will check this and let you know.

**Comment by Cristhianzl** [comment]
@596050

Due to some GitHub CI issues with the tests, I had to make several refactors. As a result, I need to close this PR. You can continue contributing from this new PR: https://github.com/langflow-ai/langflow/pull/2407.

Thank you very much for your help with this part.

I will close this PR, ok?

**Pull request closed without merging**
