### PR TITLE
Added MistralAI LLM and Embedding

### PR DESCRIPTION
**Pull request by h-arnold**
Added MistralAI LLM component and embedding component.

### CODE REVIEW

**Review by ogabrielluiz — CHANGES_REQUESTED** [review]
Hey @h-arnold 

This is looking good. Thank you! 

Could you add the Mistral ModelSpec too ? 

It should almost the same as the Model but it returns BaseLanguageModel, you can take a look at the others for guidance.

**Comment by h-arnold** [comment]
Hey @ogabrielluiz !

No problem! I'll take a look at getting the model_spec sorted. There's no MistalAI baseChatModel class either official or community so that'll take a little more work than the other ones which pretty much mirror the OpenAI spec but with mistral specific details. I'll let you know when I figure it out. :)

**Comment by h-arnold** [comment]
Hey @ogabrielluiz!

The model specs have been added and seem to work. :) Let me know if there are any issues at your end.

**Review by ogabrielluiz — APPROVED** [review]
LGTM

**Pull request merged**
