### PR TITLE
feat: add component clickhouse for vector database

### PR DESCRIPTION
**Pull request by MarceloNunesAlves**
This PR is about including the Clickhouse component as a database for embedding.

### CODE REVIEW

**Comment by MarceloNunesAlves** [comment]
Hi @ogabrielluiz,
I included a new component, and for it to work I needed to add a library to poetry but there was an error in the "Check Poetry lock" validation but I don't know what it is.

**Comment by ogabrielluiz** [comment]
Hey @MarceloNunesAlves 

Thanks for this component! 


This is probably happening because you are creating a PR from your main branch

**Comment by MarceloNunesAlves** [comment]
> Hey @MarceloNunesAlves
> 
> Thanks for this component!
> 
> This is probably happening because you are creating a PR from your main branch

Do you think I should create a new PR?

The error is about an error 403 HTTP.

**Comment by MarceloNunesAlves** [comment]
Hi @ogabrielluiz,

I understood what happened (autofix.ci / Check Poetry lock), the problem occurs because I don't have write access to the repository, and since this PR came from a fork it ended up giving this error when adding a comment (Posting diff to new comment.).
I believe that if you run that part it will work correctly.

Thank you so much!

**Review by ogabrielluiz — APPROVED** [review]

**Pull request merged**
