### PR TITLE
Feat: Add types to functions, components and hooks that are missing it

### PR DESCRIPTION
**Pull request by igorrCarvalho**
This PR adds types to all functions and components that were previously missing them.

### CODE REVIEW

**Review by zzzming — COMMENTED** [review]
Is this PR merging to main or dev?

**Comment by igorrCarvalho** [comment]
> Is this PR merging to main or dev?

Merging on dev. Ive fixed it. Thanks!

**Review by anovazzi1 — APPROVED** [review]
LGTM

**Review by anovazzi1 — CHANGES_REQUESTED** [review]
too much outdated, need some cherry pick in the types commit

**Comment by anovazzi1** [comment]
this branch is broken and is too far from the current dev branch

**Pull request closed without merging**
