### PR TITLE
fix: simplify input field handling in InputListComponent

### PR DESCRIPTION
**Pull request by Cristhianzl**
This pull request makes several changes to the `InputListComponent` in `src/frontend/src/components/core/parameterRenderComponent/components/inputListComponent/index.tsx`. The changes focus on simplifying the logic for adding and removing input fields and improving the component's overall readability.

Key changes include:

* Simplified the conditional logic for the `onClick` event handler to determine whether to add or remove an input field.
* Removed redundant conditional checks for the `data-testid` attribute and the `IconComponent` name property.

image

### CODE REVIEW

**Review by anovazzi1 — CHANGES_REQUESTED** [review]
this reverts the changes of #4890 that enables the user to delete the first field of a list of inputs

**Comment by Cristhianzl** [comment]
> this reverts the changes of #4890 that enables the user to delete the first field of a list of inputs

I will fix the UI without removing the delete action

**Comment by Cristhianzl** [comment]
image

**Review by anovazzi1 — APPROVED** [review]
lgtm

**Pull request merged**
