### PR TITLE
feat(component): implement directory component enhancements

### PR DESCRIPTION
**Pull request by raphaelchristi**
# Directory Component Improvements

Implements two key improvements to the Directory component:

## 1. Changes 'Types' field to dropdown format

**Before:**
```python
MessageTextInput(
    name="types",
    display_name="Types",
    info="File types to load. Leave empty to load all default supported types.",
    is_list=True,
)
```

**After:**
```python
DropdownInput(
    name="types",
    display_name="Types",
    info="File types to load. Select types or leave empty to load all supported types.",
    options=TEXT_FILE_TYPES,
    value=TEXT_FILE_TYPES[0],
)
```

## 2. Sets default path to current directory

```python
MessageTextInput(
    name="path",
    display_name="Path",
    info="Path to the directory to load files from. Defaults to current directory ('.')",
    value=".",
)
```

### Improvements

* Provides a clearer file type selection interface
* Sets a sensible default path
* Adds better tooltip information about the default directory

### CODE REVIEW

**Comment by erichare** [comment]
Very nice improvements @raphaelchristi , thank you!

**Comment by raphaelchristi** [comment]
> Very nice improvements @raphaelchristi , thank you!
> 
> EDIT: @raphaelchristi i just realized, i dont think the DropdownInput supports multi-select... 

Thanks @erichare 
That's a good point... Which input do you suggest for this implementation?

**Comment by erichare** [comment]
> > Very nice improvements @raphaelchristi , thank you!
> > EDIT: @raphaelchristi i just realized, i dont think the DropdownInput supports multi-select...
> 
> Thanks @erichare That's a good point... Which input do you suggest for this implementation?
> 
> EDIT: I think to accept multi-select we can do something like:
> 
> ```
>         StrInput(
>             name="types",
>             display_name="Types",
>             info="File types to load (comma-separated). Leave empty to load all supported types.",
>             value=",".join(TEXT_FILE_TYPES[0:3]),  # Default to first 3 types
>             list=True,  # This will allow multiple values
>         ),
>         
> ```

This is good!

Can you check the mypy linting issues here?

**Review by erichare — CHANGES_REQUESTED** [review]
Mypy failures are the main thing here.

**Comment by raphaelchristi** [comment]
> Mypy failures are the main thing here.

Thanks for the review @erichare ! 

I checked the mypy linting and it's passing without any issues now.
image

**Review by erichare — APPROVED** [review]

**Comment by erichare** [comment]
Thanks @raphaelchristi !!

**Pull request merged**
