### PR TITLE
zep: Memory and Retriever

### PR DESCRIPTION
**Pull request by danielchalef**
@ogabrielluiz Rough attempts at `ZepMemory` and `ZepMemoryRetriever` components.

I added a `components/memory` directory. I wasn't sure how to wire up LangFlow so that it loads components in this new directory.

How do I automatically populate the `session_id` field with a unique identifier for the current chat session?

### CODE REVIEW

**Comment by ogabrielluiz** [comment]
Hey, Daniel! Thanks for the new components. 

For Langflow to pick them up you gotta name the folder one of the categories in config.yaml in the langflow folder. I think it should be `components/memories`.

Onto the questions: 
1. Inside the build_config method, if you pass a list of strings to the `options` key and make the parameter of the type `str` a drop-down should pop up. You can run any type of logic inside build_config to get the values you want. 

2. I think a good way would be to make the parameter optional and generate a random one inside the function, then put a `info` field telling the user that if no value is passed a random one will be generated. Something like that... What do you think? 

3. The `optional` key is not valid. It should be passed as a type hint in the build method importing from `typing`. About the password param, I'll check if there's something wrong with it first thing in the morning. 

Thanks again and please, let me know if there's something you feel is missing for the best use of Zep's features.

**Comment by danielchalef** [comment]
@ogabrielluiz I solved the issue with rendering of field names and the drop-down. I needed to rebuild the front-end. I've also got the ZepMemory component working.

The session_id is generated by the developer's code for each unique chat session. Is there a way to require a developer does this via code when running the flow?

**Comment by ogabrielluiz** [comment]
No, but there are options that we can experiment with:
1. We can create a new type of field that generates random strings when clicked
2.	Make the `session_id` `Optional[str] = None` and create a condition in the `build` method to generate a random one. 
3. Build a CustomComponent that generates random strings and allow the user to connect to the field (this one is not ideal because this would add a component that is too specific).

**Comment by Elsayed91** [comment]
Any updates on this?

**Comment by danielchalef** [comment]
Hey @Elsayed91 , I've been heads down working on some other projects. Hope to get back to this soon!

**Comment by ogabrielluiz** [comment]
Hey, Daniel! 

We've added an experimental feature that allows you to pass a callable to `options` in the custom component.

Something like:
```python 

class Component(CustomComponent):
	...
	def get_uuid(self):
		return "A_UUID"
	
	def build_config(self):
		return {"unique_id": {"options":self.get_uuid}}

	def build(unique_id:str):
		...
```

Let me know if that solves your issue.

**Pull request closed without merging**
