### PR TITLE
build: fix astra integration tests

### PR DESCRIPTION
**Pull request by jordanrfrazier**
Fixes the astra integ tests.

### CODE REVIEW

**Review by ogabrielluiz — CHANGES_REQUESTED** [review]
Thanks, @jordanrfrazier 

Just remove the print and should be good to go.

**Review by ogabrielluiz — APPROVED** [review]

**Comment by jordanrfrazier** [comment]
Fixing env var access

**Comment by ogabrielluiz** [comment]
> Fixing env var access

Sorry haha

**Comment by jordanrfrazier** [comment]
> > Fixing env var access
> 
> Sorry haha

Haha did you change something? This was a mistake on my end -- I have the naming incorrect in th eworkflow.

**Review by nicoloboschi — APPROVED** [review]

**Pull request merged**
