### PR TITLE
feat: Add Branding and Social Links to the UI Feature flags

### PR DESCRIPTION
**Pull request by mfortman11**
Now allows users to toggle on/off DataStax branding and Langflow social links

### CODE REVIEW

**Comment by ogabrielluiz** [comment]
Hey @mfortman11 

How are you? 

How does this work on pip install? Will these be added on the build step or will the user be able to change later as well?

**Review by anovazzi1 — APPROVED** [review]
LGTM

**Comment by codenprogressive** [comment]
Hey @mfortman11 

I was going to ask the same question as Ogabrielluiz. 
How are we going to change those variables `ENABLE_SOCIAL_LINKS` and `ENABLE_BRANDING` ? Can we change them in the .env file [https://github.com/langflow-ai/langflow/blob/main/.env.example](https://github.com/langflow-ai/langflow/blob/main/.env.example)?

**Comment by buntys2010** [comment]
@codenprogressive You can set this flags from src/frontend/src/customization/feature-flags.ts file.

**Comment by juanvecino** [comment]
And what about if you're using a DockerFile like:

```
FROM langflowai/langflow:latest

COPY custom_components /app/custom_components

CMD ["sh", "-c", "python -m langflow run --host 0.0.0.0 --port 7860"]
```

I want my code to be able to change with new updates of Langflow..

**Pull request merged**
