### PR TITLE
docs: add kubernetes deployment

### PR DESCRIPTION
**Pull request by nicoloboschi**
This is a doc for kubernetes deployment steps using helm charts that is published https://github.com/langflow-ai/langflow-helm-charts

### CODE REVIEW

**Review by zzzming — APPROVED** [review]

**Review by mendonk — APPROVED** [review]
Thanks Nicolo, looks good to me

**Review by NadirJ — APPROVED** [review]

**Review by ogabrielluiz — COMMENTED** [review]
Hey @nicoloboschi 

Will Kubernetes have 'sticky sessions' if I scale it up? 
Should we add a Redis setup on these docs? 

Asking this because if using streaming the API won't be as stateless because we need to get the built graph from the cache.

**Review by zzzming — APPROVED** [review]
Verified helm steps on x86

**Comment by zzzming** [comment]
> Hey @nicoloboschi
> 
> Will Kubernetes have 'sticky sessions' if I scale it up? Should we add a Redis setup on these docs?
> 
> Asking this because if using streaming the API won't be as stateless because we need to get the built graph from the cache.

@ogabrielluiz the current chart (https://github.com/langflow-ai/langflow-helm-charts/tree/main/charts/langflow-ide/templates) does not include Redis. 

We can add the Redis in the https://github.com/langflow-ai/langflow-helm-charts/tree/main/charts/langflow-ide/templates
However, the procedure of provision the chart should be the same.

The procedure looks good and verified.

**Pull request merged**
