### PR TITLE
fix: modified DirectoryDataComponent to support user defined custom file types

### PR DESCRIPTION
**Pull request by EDLLT**
Fixes https://github.com/langflow-ai/langflow/issues/4012

- fix: modified DirectoryDataComponent to support user defined custom file types
- test_data_components.py: Updated 'test_directory_component_build_with_multithreading' to expect an extra argument

### CODE REVIEW

**Comment by EDLLT** [comment]
@dosu 
What is this and why is it failing?
<details>
<summary>CI Logs</summary>
0s
Run echo $JOBS_JSON
  echo $JOBS_JSON
  echo $RESULTS_JSON
  echo "Exiting with $EXIT_CODE"
  exit $EXIT_CODE
  shell: /usr/bin/bash -e {0}
  env:
    JOBS_JSON: {
    "test-backend": {
      "result": "skipped",
      "outputs": {}
    },
    "test-frontend": {
      "result": "skipped",
      "outputs": {}
    },
    "lint-backend": {
      "result": "skipped",
      "outputs": {}
    },
    "test-docs-build": {
      "result": "skipped",
      "outputs": {}
    },
    "set-ci-condition": {
      "result": "success",
      "outputs": {
        "should-run-ci": "false"
      }
    }
  }
    RESULTS_JSON: [
    "skipped",
    "skipped",
    "skipped",
    "skipped",
    "success"
  ]
    EXIT_CODE: [1](https://github.com/langflow-ai/langflow/actions/runs/11169601064/job/31050687782?pr=4017#step:2:1)
{ "test-backend": { "result": "skipped", "outputs": {} }, "test-frontend": { "result": "skipped", "outputs": {} }, "lint-backend": { "result": "skipped", "outputs": {} }, "test-docs-build": { "result": "skipped", "outputs": {} }, "set-ci-condition": { "result": "success", "outputs": { "should-run-ci": "false" } } }
[ "skipped", "skipped", "skipped", "skipped", "success" ]
Exiting with 1
Error: Process completed with exit code 1.
</details>

**Review by ogabrielluiz — APPROVED** [review]
Hey @EDLLT 

Thanks for this. 

LGTM

**Comment by EDLLT** [comment]
This CI Error looks unrelated to changes made in this PR as well

```
=========================== short test summary info ============================
FAILED src/backend/tests/unit/test_data_components.py::test_directory_component_build_with_multithreading - AssertionError: expected call not found.
Expected: retrieve_file_paths('/home/runner/work/langflow/langflow/src/backend/tests/unit', False, True, 1)
  Actual: retrieve_file_paths('/home/runner/work/langflow/langflow/src/backend/tests/unit', False, True, 1, None)
```

**Comment by EDLLT** [comment]
Oops, attempting to rename the branch to "directory-fix" instead resulted in it deleting the main branch....................

**Comment by EDLLT** [comment]
It appears that specific uv test failure occurs upstream as well
```
src/backend/tests/unit/test_database.py::test_update_flow FAILED                                                                [ 62%]
__________________________________________________________ test_update_flow ___________________________________________________________

client = <httpx.AsyncClient object at 0x70edc2954140>
json_flow = '{\n  "description": "",\n  "name": "BasicExample",\n  "id": "a53f9130-f2fa-4a3e-b22a-3856d946351a",\n  "data": {\n   ...    "viewport": {\n      "x": 1,\n      "y": 0,\n      "zoom": 0.5\n    }\n  },\n  "last_tested_version": "0.6.2"\n}\n'
active_user = User(id=UUID('e6761bca-2ba5-460b-8344-aa15645aac1c'), password='$2b$12$K5sBRC2m5aa0BHaWVIn5yunp.Qljj5o8Z31jUYDLEEcn0GN...ofile_image=None, is_superuser=False, updated_at=datetime.datetime(2024, 10, 5, 12, 51, 7, 502973), store_api_key=None)
logged_in_headers = {'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjc2MWJjYS0yYmE1LTQ2MGItODM0NC1hYTE1NjQ1YWFjMWMiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MTM2MjcxfQ.N1wMUo7aQD4dy86BHY2ElJvMkgQjIPfDUQdnRt96JBo'}

    async def test_update_flow(client: TestClient, json_flow: str, active_user, logged_in_headers):
        flow = orjson.loads(json_flow)
        data = flow["data"]
    
        flow = FlowCreate(name="Test Flow", description="description", data=data)
        response = await client.post("api/v1/flows/", json=flow.model_dump(), headers=logged_in_headers)
    
        flow_id = response.json()["id"]
        updated_flow = FlowUpdate(
            name="Updated Flow",
            description="updated description",
            data=data,
        )
        response = await client.patch(f"api/v1/flows/{flow_id}", json=updated_flow.model_dump(), headers=logged_in_headers)
    
>       assert response.status_code == 200
E       assert 400 == 200
E        +  where 400 = <Response [400 Bad Request]>.status_code

src/backend/tests/unit/test_database.py:109: AssertionError
```

I'll ignore it for now and focus on fixing ``Directory.py`` uv's test failure instead

**Comment by EDLLT** [comment]
> I think I got to the root of the issue. It is indeed being caused by Directory.py 🤦
> 
> ```
> src/backend/base/langflow/components/data/Directory.py:92: in load_directory
>     loaded_data = [parse_text_file_to_data(file_path, silent_errors) for file_path in file_paths]
> ```

Okay, I fixed it. I simply had to check that self.types is valid(isn't False, an empty list, ...) as well as check it it isn't a list with an empty string rather than only checking the latter

The only ``FAILED`` instance by UV should now be one the one that also occurs upstream

**Comment by EDLLT** [comment]
Ok, seems like all the checks are passing. I'll squash the commits

**Pull request merged**
