### PR TITLE
feat: Add SimpleAgentComponent and related pytests

### PR DESCRIPTION
**Pull request by edwinjosechittilappilly**
Introduce the `SimpleAgentComponent`, a new agent component that extends `ToolCallingAgentComponent`. This component allows the agent to utilize various tools and supports both OpenAI and Azure OpenAI language models. It includes configurations for selecting the language model type and manages input types dynamically based on the selected model.

https://github.com/user-attachments/assets/d4e1b8d4-e328-43a5-81ba-2c18e8b867e5

### Changes

- **Added** `SimpleAgentComponent` class in `src/backend/base/langflow/components/agents/simple_agent.py`
- **Defined** inputs and outputs for the component, including tool handling and language model selection
- **Implemented** methods for building and managing language models (`get_llm`, `_build_llm_model`)
- **Included** error handling for model configuration and missing keys in `build_config`
- **Updated** input types dynamically based on the selected language model

### Motivation and Context

This addition enhances the agent framework by providing a straightforward agent capable of leveraging different language models and tools. It offers greater flexibility and extensibility for building complex workflows within the Langflow application.

### Future Updates: 
- Add Graph Run inside the component so we can integrate the input component and output component in the same agent.
- Ability to add Agent Name as sender Name

#### Autogenerated: PR Message

This pull request introduces a new `SimpleAgentComponent` class, adds unit tests for this component, and modifies existing tests for the `ToolCallingAgentComponent`. The key changes include the creation of the `SimpleAgentComponent` class, the addition of unit tests for both the `SimpleAgentComponent` and `ToolCallingAgentComponent`, and the integration of various input and output components.

### New Components:
* [`src/backend/base/langflow/components/agents/simple_agent.py`](diffhunk://#diff-6bcaea75d1cdcae8ab5798ab147a2956ebbf234384835993ce0a3a3a67abe42cR1-R132): Added `SimpleAgentComponent` class that extends `ToolCallingAgentComponent` to handle different language models and tools. (`[src/backend/base/langflow/components/agents/simple_agent.pyR1-R132](diffhunk://#diff-6bcaea75d1cdcae8ab5798ab147a2956ebbf234384835993ce0a3a3a67abe42cR1-R132)`)

### Unit Tests:
* [`src/backend/tests/unit/components/agents/test_simple_agent.py`](diffhunk://#diff-f2758044606f96f1378563cfaab80149810adf5f7b8b5b780b63f93d4cb8063eR1-R31): Added unit test for `SimpleAgentComponent` to verify its functionality using a calculator tool. (`[src/backend/tests/unit/components/agents/test_simple_agent.pyR1-R31](diffhunk://#diff-f2758044606f96f1378563cfaab80149810adf5f7b8b5b780b63f93d4cb8063eR1-R31)`)
* [`src/backend/tests/unit/components/agents/test_tool_calling_agent.py`](diffhunk://#diff-cb1e0fb42766434760104f00ff364c54550e4c9d2df99d66cd58fa3e06c401a4R1-R32): Added unit test for `ToolCallingAgentComponent` to ensure it can correctly use a calculator tool and produce expected outputs. (`[src/backend/tests/unit/components/agents/test_tool_calling_agent.pyR1-R32](diffhunk://#diff-cb1e0fb42766434760104f00ff364c54550e4c9d2df99d66cd58fa3e06c401a4R1-R32)`)

### CODE REVIEW

**Review by italojohnny — APPROVED** [review]
Amazing work!

**Comment by edwinjosechittilappilly** [comment]
Thank you @italojohnny

**Comment by edwinjosechittilappilly** [comment]
@Cristhianzl  Any suggestion on why the FrontEnd Test Group 4 always fails in this PR?

**Comment by edwinjosechittilappilly** [comment]
> @Cristhianzl Any suggestion on why the FrontEnd Test Group 4 always fails in this PR?

Found the Error: The simplified Agent is having the name just Agent and the starter template simple Agent Flow is based of the tool calling agent. We might need to update the started template so solve this issue

**Comment by edwinjosechittilappilly** [comment]
> > @Cristhianzl Any suggestion on why the FrontEnd Test Group 4 always fails in this PR?
> 
> Found the Error: The simplified Agent is having the name just Agent and the starter template simple Agent Flow is based of the tool calling agent. We might need to update the started template so solve this issue

Updated the Agent Flow.json to use the Agent component instead of the tool calling agent, still the test fails.

**Pull request merged**
