### PR TITLE
feat: new Vectara RAG Component

### PR DESCRIPTION
**Pull request by david-oplatka**
This component implements the full Vectara RAG pipeline. New changes:

* End-to-end RAG with summarization prompts from Vectara (does not require additional OpenAI key)
* Supports Vectara's new [reranker](https://vectara.com/blog/unlocking-the-state-of-the-art-reranker-introducing-the-vectara-multilingual-reranker_v1/)

### CODE REVIEW

**Comment by ogabrielluiz** [comment]
Hey @david-oplatka 

Thanks for the PR.

I've changed the base to `main` because we don't have a `dev` branch anymore.

**Comment by ofermend** [comment]
Thanks @ogabrielluiz - anything else needed?

**Review by ogabrielluiz — APPROVED** [review]

**Comment by ogabrielluiz** [comment]
Hey @ofermend 

I've updated the component. If it is working as intended by @david-oplatka. We can merge it.

**Comment by ofermend** [comment]
SG. Let's merge then - thanks!

**Comment by LakshmiBhaskarPVL** [comment]
damn good !!

**Pull request merged**
