### PR TITLE
Fix flow settings validation and save button

### PR DESCRIPTION
**Pull request by anovazzi1**
This pull request fixes the validation and save button behavior in the flow settings modal. Previously, the save button was not disabled when it should have been, and the endpoint name validation was not working correctly. This PR updates the validation logic and ensures that the save button is disabled when necessary.

### CODE REVIEW

**Comment by vasconceloscezar** [comment]
When I just change the description, it throws an error about endpoint error name, making me put something as the name. 

image

**Review by ogabrielluiz — APPROVED** [review]
LGTM

**Comment by vasconceloscezar** [comment]
Kinda as it was before, but with a wierder behavior. 

It doesn't matter if I change the description or the endpoint, it doesn't activate the save button.
The endpoint is saving "on its own", even without clicking save, if I edit it and close the modal, the value was saved there.

https://jam.dev/c/b6188fa8-c13f-4efc-b212-e3c970e15a0e

**Review by vasconceloscezar — APPROVED** [review]

**Review by carlosrcoelho — APPROVED** [review]
Approved

**Pull request merged**
