### PR TITLE
fix: narrow version ranges for project dependencies

### PR DESCRIPTION
**Pull request by italojohnny**
This PR aims to address the installation issues of the project package via pip. To simplify dependency resolution, the version ranges of dependencies have been replaced with exact versions to avoid conflicts during pip installation.

The package installation has been tested with Python versions 3.10, 3.11, and 3.12.

### CODE REVIEW

**Comment by erichare** [comment]
@italojohnny I definitely like this, but just wondering, do you think == is better than ~= in general? Only asking because i thought it kind of makes sense to allow minor version increments, but maybe that still causes dependency resolution issues?

**Comment by italojohnny** [comment]
> I definitely like this, but just wondering, do you think == is better than ~= in general? Only asking because i thought it kind of makes sense to allow minor version increments, but maybe that still causes dependency resolution issues?

@erichare,  I performed a quick test where I replaced `==` with `~=` in the dependency specifications, generated the package, and attempted to install it in virtual environments using pip: all attempts timed out while trying to resolve dependencies.

I admit my solution is quite rudimentary, but it solves the problem without considering other factors.
If anyone remembers something I might be overlooking, please let us know.

**Review by erichare — APPROVED** [review]

**Comment by erichare** [comment]
> > I definitely like this, but just wondering, do you think == is better than ~= in general? Only asking because i thought it kind of makes sense to allow minor version increments, but maybe that still causes dependency resolution issues?
> 
> @erichare, I performed a quick test where I replaced `==` with `~=` in the dependency specifications, generated the package, and attempted to install it in virtual environments using pip: all attempts timed out while trying to resolve dependencies.
> 
> I admit my solution is quite rudimentary, but it solves the problem without considering other factors. If anyone remembers something I might be overlooking, please let us know.

Probably specifying exact versions is the safest bet anyway 😄 i'll approve! when i worked on the langchain upgrade PR, i switched a lot of `>=` version dependencies to `~=` hoping that would solve the problem, but if the resolver is still struggling i think its all the more reason just to fix everything as much as possible. We'll just want to constantly keep a watch on both critical bugfixes and feature releases that we might be missing... hopefully as the community-provided components get more capable that will be less of a concern!

**Comment by ogabrielluiz** [comment]
Using ~= is pretty useful so we don't block other projects but also to grab bug fixes in other projects. It won't be as open as >= so it isn't as problematic.

**Review by ogabrielluiz — APPROVED** [review]

**Pull request merged**
