### PR TITLE
fix: add hover state on folder button when moving flow to it

### PR DESCRIPTION
**Pull request by Cristhianzl**
This pull request makes several changes to the `SideBarFoldersButtonsComponent` in the `index.tsx` file to improve the component's functionality and readability. The most important changes include reordering the hooks and state variables, adding new hooks for folder operations, and updating the component's class names for better folder interaction.

### Reordering and Grouping Hooks and State Variables:
* Reordered the hooks and state variables for better readability and logical grouping.

### Adding New Hooks for Folder Operations:
* Added hooks for folder operations such as `useGetDownloadFolders`, `usePostFolders`, and `usePatchFolders`. [[1]](diffhunk://#diff-c555da19c21570f424bb71bd92a075b37bbe7be3fbc75387b03b37728a8dc9cfL57-R118) [[2]](diffhunk://#diff-c555da19c21570f424bb71bd92a075b37bbe7be3fbc75387b03b37728a8dc9cfL128-L129) [[3]](diffhunk://#diff-c555da19c21570f424bb71bd92a075b37bbe7be3fbc75387b03b37728a8dc9cfL169-L171)

### Updating Class Names for Folder Interaction:
* Updated class names in the component to handle folder hovering and active states using the `checkHoveringFolder` and `checkPathName` methods. [[1]](diffhunk://#diff-c555da19c21570f424bb71bd92a075b37bbe7be3fbc75387b03b37728a8dc9cfL443-R454) [[2]](diffhunk://#diff-c555da19c21570f424bb71bd92a075b37bbe7be3fbc75387b03b37728a8dc9cfL510-R526)

These changes enhance the component's structure, making it easier to manage folder operations and improving user interaction with the sidebar folders.

### CODE REVIEW

**Review by lucaseduoli — CHANGES_REQUESTED** [review]
Flows losing description when moving from folder to another

**Comment by Cristhianzl** [comment]
> Flows losing description when moving from folder to another

please, check again!

**Review by lucaseduoli — CHANGES_REQUESTED** [review]
i think it would be better to not use one more state on useFolderStore for that, and just filter the flows by folder id equal to the one that we want

**Review by lucaseduoli — APPROVED** [review]
LGTM

**Pull request merged**
