### PR TITLE
Add LangWatch Integration

### PR DESCRIPTION
**Pull request by rogeriochaves**
Hello there 👋 

This PR adds LangWatch integration as a TracingService, I took the liberty of making some small improvements on the TracingService itself which helped getting a better logging, like passing the `vertex` as an argument so we can link hierarchically the components and masking the api_keys by default for security.

- [x] Add base LangWatch Integration
- [x] Convert inputs, outputs and error messages to have the best debugging experience on langwatch
- [x] Add parent-child hierarchy
- [x] Add docs
- [x] Tested with various workflows and fixed edge cases 
- [x] Truncate input/output when it's too large for observability, like reading files for example

Some examples of it running:

| Flow | Trace |
| - | - |
| Two Outputs image | image |
| Agent Tool Calling image | image |
| Calling 3 LLMs to choose the best summary image | image |
| Thread Visualization image | image |
| Message list visualization image | Table visualization Screenshot 2024-07-09 at 19 21 51 | 

Then I'll leave somethings for next iterations which might take a bit longer:

- [ ] Consider adding support for multiple parents on LangWatch, so we can represent it as a graph also on LangWatch side
- [ ] Consider adding the langchain callback to track also the steps that happen inside the agents and other tools
- [ ] Explore how we can capture explicitly the RAG contexts so RAG evaluations can be used on LangWatch side

### CODE REVIEW

**Comment by rogeriochaves** [comment]
I'm having an issue with dependencies:

```
Because no versions of langwatch match >0.1.4,<0.2.0
 and langwatch (0.1.4) depends on pandas (>=2.2.2,<3.0.0), langwatch (>=0.1.4,<0.2.0) requires pandas (>=2.2.2,<3.0.0).
And because langflow-base (0.0.81) depends on pandas (2.2.0)
 and no versions of langflow-base match >0.0.81,<0.0.82, langwatch (>=0.1.4,<0.2.0) is incompatible with langflow-base (>=0.0.81,<0.0.82).
So, because langflow depends on both langflow-base (^0.0.81) and langwatch (^0.1.4), version solving failed.
```

however I did upgrade pandas to 2.2.2 already inside the `backend/base/pyproject.toml`, how can I proceed? Should I create another MR just bumping pandas version beforehand?

**Comment by ogabrielluiz** [comment]
Hey @rogeriochaves 

Thank you for this PR. This looks really awesome. 

You had the wrong base branch. You should use the main branch for this. Could you merge your PR with the main branch?

**Comment by rogeriochaves** [comment]
@ogabrielluiz oh, sorry, I was told to use the dev branch, but now I see I opened a PR agains main anyway, my bad then, will move over then!

**Comment by ogabrielluiz** [comment]
> @ogabrielluiz oh, sorry, I was told to use the dev branch, but now I see I opened a PR against main anyway, my bad then, will move over then!

I changed it for you. All you got to do is fix these conflicts and you should be good to go. Maybe rebase from main.

**Comment by rogeriochaves** [comment]
@ogabrielluiz okay, pipeline is green now, ready to merge!

one note not related to the changes in this PR, but that I noticed after rebasing with main, now the tracing service only works when calling it through the API, no longer when running individual components or on the playground. Is that expected?

**Comment by ogabrielluiz** [comment]
> @ogabrielluiz okay, pipeline is green now, ready to merge!
> 
> one note not related to the changes in this PR, but that I noticed after rebasing with main, now the tracing service only works when calling it through the API, no longer when running individual components or on the playground. Is that expected?

No. It shouldn't be like that. I'll take a look

**Comment by rogeriochaves** [comment]
@ogabrielluiz all good to merge again

**Review by ogabrielluiz — APPROVED** [review]

**Pull request merged**
