### PR TITLE
Add i18n to the frontend

### PR DESCRIPTION
**Pull request by skipandsnow**
Merged 2 pull request #2149 #2242, complete the missing translation part and add traditional chinese.

### CODE REVIEW

**Comment by ogabrielluiz** [comment]
This is so awesome @skipandsnow 

I can't thank you enough.

Should we go through defining a way to set it up on the settings page ?

@anovazzi1 what do you think?

**Comment by anovazzi1** [comment]
I think this is a good idea, maybe a language dropdown in the settings page?

**Comment by skipandsnow** [comment]
> I think this is a good idea, maybe a language dropdown in the settings page?

I would like to help with it :)

**Comment by ogabrielluiz** [comment]
Hey @skipandsnow 

We are going to prioritize the #2149 since it was created first. Do you mind merging this one into it? Or we can merge it first, then we merge yours. What do you think?

**Pull request closed without merging**
