### PR TITLE
FEAT: Upgrade langchain (0.3.x) and associated packages including langchain-astradb

### PR DESCRIPTION
**Pull request by erichare**
This upgrades our langchain dependency to 0.3.x, adds ~= requirements to associated packages, and allows the use of the latest `langchain-astradb` as a result.

### CODE REVIEW

**Comment by edwinjosechittilappilly** [comment]
Did you encounter any issues with Pydantic when installing and running the backend? @erichare

**Comment by erichare** [comment]
> Did you encounter any issues with Pydantic when installing and running the backend of Langflow after the upgrade to 0.3.x? @erichare

I admit i haven't extensively tested it, would love some help from others, but i was able to build and start the backend service without problems. I was also able to run my existing flows i had saved. I do see depcration warnings about pydantic:

```
Starting Langflow v1.0.19...
/Users/erichare/GitHub/langflow/src/backend/base/langflow/utils/validate.py:224: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.
```

But it doesn't appear to block the startup. question is whether we would like to go through and remove references to pydantic_v1, or defer that for later?

**Comment by edwinjosechittilappilly** [comment]
> > Did you encounter any issues with Pydantic when installing and running the backend of Langflow after the upgrade to 0.3.x? @erichare
> 
> I admit i haven't extensively tested it, would love some help from others, but i was able to build and start the backend service without problems. I was also able to run my existing flows i had saved. I do see deprecation warnings about pydantic:
> 
> ```
> Starting Langflow v1.0.19...
> /Users/erichare/GitHub/langflow/src/backend/base/langflow/utils/validate.py:224: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.
> ```
> 
> But it doesn't appear to block the startup. question is whether we would like to go through and remove references to pydantic_v1, or defer that for later?

Thats cool. Earlier when I tried the upgrade I faced some Pydantic upgrade error. 
Let me review it and shall let you know soon.

**Comment by edwinjosechittilappilly** [comment]
Tested. Looks good to me. 
The SecretStr error I observed earlier seems to be managed. Perhaps, as a follow-up pull request, we can add a chore to upgrade Pydantic from version 2.0 to 3.0 in some functionalities.

**Comment by edwinjosechittilappilly** [comment]
@erichare  can you resolve the conflicts in uv.lock?

**Review by cbornet — APPROVED** [review]

**Review by edwinjosechittilappilly — APPROVED** [review]
LGTM

**Pull request merged**
