### PR TITLE
ref: Remove sync Graph.step()

### PR DESCRIPTION
**Pull request by cbornet**
Remove sync Graph.step()

### CODE REVIEW

**Review by ogabrielluiz — COMMENTED** [review]
Are we replacing it with something else?

**Comment by cbornet** [comment]
> Are we replacing it with something else?

We only keep the async version. Do we need a sync one ?

**Comment by ogabrielluiz** [comment]
Users normally use sync functions.

**Comment by cbornet** [comment]
Users would call step() directly ?

**Comment by ogabrielluiz** [comment]
Step would be a user facing api so I don't see why not. It could be useful to design a human-in-the-loop Graph, for example

**Pull request closed without merging**
