### PR TITLE
Fix: simple agent template notes

### PR DESCRIPTION
**Pull request by mendonk**
* Remove youtube starter template
* Replace existing simple agent.json with updated readme, description, and key node.

Screenshot 2024-11-19 at 11 28 30 AM

### CODE REVIEW

**Review by NadirJ — APPROVED** [review]

**Comment by ogabrielluiz** [comment]
Hey @mendonk 

The conflicts are just due to formatting. If you fix them, please run the backend once to make sure the formatting is correct.

**Comment by ogabrielluiz** [comment]
Hey @mendonk there's probably something wrong with the JSON you added.

**Comment by edwinjosechittilappilly** [comment]
@mendonk Docs are spinning up.
Investigating why the playwright tests failed!

**Comment by mendonk** [comment]
@edwinjosechittilappilly the docs are OK
The JSON issue yesterday was because I didn't have a [tag] in the file
Try to start the simple-agent starter template flow in this branch, that's where the issue im seeing is

**Comment by edwinjosechittilappilly** [comment]
Error in Simple agent flow template:

Flow is Saved correctly, But when loaded as a template, the edges from the URL component as Tools to the agent are missing.
@ogabrielluiz.
We are not updating the flows anywhere in front end, right?

**Pull request merged**
